---
_extends: klaasnicolaas/.github
tag-template: "$RESOLVED_VERSION"

template: |
  ## What's changed

  _To receive a notification on new releases, click on **Watch** > **Custom** > **Releases** on the top._

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
