---
# Home Assistant Glow - basic (no status LED)
#
# Read your electricity meter by means of the pulse LED on your
# meter, useful if you do not have a serial port (P1).
# © Klaas Schoute
#
substitutions:
  device_name: home-assistant-glow
  friendly_name: Home Assistant Glow
  project_version: "4.3.1"
  device_description: "Measure your energy consumption with the pulse LED on your smart meter - ESP32 Generic (basic)"
  update_manifest_url: "https://glow-energy.io/glow-basic/manifest.json"

  # Define the GPIO pins
  pulse_pin: GPIO26

esphome:
  name: '${device_name}'
  comment: '${device_description}'
  name_add_mac_suffix: true
  min_version: 2025.11.0
  project:
    name: "klaasnicolaas.home-assistant-glow"
    version: "${project_version}"

dashboard_import:
  package_import_url: github://klaasnicolaas/home-assistant-glow/glow-basic/esp32.yaml@main

esp32:
  variant: esp32
  framework:
    type: esp-idf

packages:
  remote_package:
    url: https://github.com/klaasnicolaas/home-assistant-glow/
    ref: "4.3.1"
    files:
      - components/basis.yaml
      - components/updates.yaml
      - components/pulse_meter.yaml

# No LED in basic variant
script:
  - id: on_pulse
    then: []

# Enable logging
logger:

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap:
    ssid: '${friendly_name}'

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

# Local Web Server running on port 80
web_server:
  id: esphome_web_server
  version: 3
