import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docSidebar: [
    'introduction',
    'getting-started',
    {
      type: 'category',
      collapsed: false,
      label: 'Configuration',
      items: [
        'configuration/pulse_rate',
        'configuration/rename',
        'configuration/energy_dashboard',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        'advanced/firmware_customization',
      ],
    },
    {
      type: 'category',
      collapsed: false,
      label: 'Resources',
      items: [
        'resources/schematics',
        'resources/gpio',
        'resources/cases',
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  // faqSidebar: [{type: "autogenerated", dirName: "faq"}],
  faqSidebar: [
    {
      type: 'category',
      label: 'Frequency Asked Questions',
      link: {
        type: 'generated-index',
        slug: 'faq',
        description: 'The answers to the most common questions.'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'faq',
        }
      ]
    },
  ],
};

export default sidebars;
