---
name: Tweet on Release

# yamllint disable-line rule:truthy
on:
  release:
    types: [published]

jobs:
  twitter:
    name: 🐦 Tweet the release
    runs-on: ubuntu-latest
    steps:
      - uses: Eomm/why-don-t-you-tweet@v2.0.0
        with:
          # GitHub event payload
          # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release
          tweet-message: |
            ⬆️ ${{ github.event.release.tag_name }} of ${{ github.event.repository.name }} just released 🎉 #update @klaasnicolaas @home_assistant #glow #energy #esphome #release #bot #assistant

            Check out the release notes here: ${{ github.event.release.html_url }}
        env:
          # Get your tokens from https://developer.twitter.com/apps
          TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
